name: GitHub Packages
on: [push]
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build and Deploy
        working-directory: ./src/LibNMeCab
        run: |
          nuget restore LibNMeCab.csproj
          dotnet build
          dotnet nuget add source --username egon-r --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/egon-r/index.json"
          nuget pack -Properties Configuration=Release
          ls .
          
